apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume-test
  labels:
    type: local
    tier: test
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain #Recycle, Delete
  #mountOptions:
  # - hard
  # - nfsvers=4.1
  #nfs:
  # path: /tmp
  # server: 172.17.0.2
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim-test
  namespace: test
  labels:
    tier: test
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: test
  labels:
    tier: test
    app: postgres

spec:
  replicas: 1
  selector:
    matchLabels:
      tier: test
      app: postgres
  template:
    metadata:
      labels:
        tier: test
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          #envFrom:
          #  - configMapRef:
          #      name: postgres-config
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-test-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgresql-test-secret
                key: POSTGRES_USER
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgresql-test-secret
                key: POSTGRES_DATABASE
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      nodeSelector:
        tier: test
      tolerations:
      - key: "tier"
        operator: "Equal"
        value: "test"
        effect: "NoSchedule"
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim-test
---
apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: postgres
  labels:
    tier: test
    app: postgres
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    tier: test
    app: postgres